Home page of Mobile Version skeleton
IfzaRasool/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2021-11-26 01:58 UTC by IfzaRasool

Portfolio setup and mobile version skeleton:
In this project, we make a mobile version skeleton .simple template that I make using the Figma UI tool. Figma tool is used to easily create a project template skeleton. here we use just two languages HTML and CSS with proper semantic rules and Linters checker.

2021-11-26 02:59 UTC, moise10r requested changes
### Hi @IfzaRasool  

Good job so far for implementing this project! :smiley: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️

- [ ] Please let follow exactly the Figma design.

| Figma Design  |  Your Design  | 
|---|---|
| ![orr](https://user-images.githubusercontent.com/57562869/143519927-8a2283cf-fe7e-4d18-bec3-1fbaca485f4d.png)| ![or](https://user-images.githubusercontent.com/57562869/143519969-d044ed59-a118-45a4-a084-a00bb451a8ca.png)|   

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 02:59 UTC, moise10r commented on index.html
> +           <a class="nav-bar"><img src="Icons/Union.png" alt="nevigation image"></a>
- [ ] Great Job while implementing this project, kindly put the logo in an `a` tag instead of  `h1` tag and the hamburger should be in the `nav` tag.

2021-11-26 02:59 UTC, moise10r commented on index.html
>              <ul class="inside-lang-panal">
- [ ] Very nice for implementing the headline section but remember this section should be in a `section` tag, can you please check that out and change it to `section` tag instead of `div` tag? :woman_technologist:

2021-11-26 02:59 UTC, moise10r commented on index.html
> +        <img src="Icons/twitter.png" alt ="twitter logo">
- [ ] Great job for adding the social media section in your portfolio, just, we need again to work on just to code it like a pro. Can you please put the social media icons in a list as long as is a list of social media, just like this below:
```HTML
  <ul class="social-media-list">
     <li class="social-media-item"></li> 
 </ul>
```

2021-11-26 22:58 UTC, MrBrN197 requested changes
## Hi,  @IfzaRasool 👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 22:58 UTC, MrBrN197 commented on index.html
> +           <a class="logo">Ifza Rasool</a>
- [ ] [OPTIONAL] Well done including a link on the logo text 👍. However if you notice most websites when you click the logo text it directs the users to the homepage. so you can specify a `href` back so it can have that functionality.

something like this would be nice. 
```suggestion
           <a href="/" class="logo">Ifza Rasool</a>
```

2021-11-26 22:58 UTC, MrBrN197 commented on index.html
> +           <h3 class="lang-panal-head">Language</h3>
- [ ] Hi as the previous reviewer requested please implement this as a `section`. you can put all the `div`s inside one `section` tag and leave the `header` out. the reason we want a `section` is to insure good usage of correct HTML semantics 👍.

2021-11-26 22:58 UTC, MrBrN197 commented on styles.css
>  /* stylelint-disable block-closing-brace-empty-line-beforee */
- [ ] [ OPTIONAL] you've used three Stylelint disables here. please avoid disabling ESlint rules. they are there to ensure a good and clean code style please try instead to fix the errors. you can use the `--fix` flag to try and automatically fix the errors. You can also install the ESlint VSCode extension and set it up to automatically fix your errors when you save 👍.

2021-11-26 22:58 UTC, MrBrN197 commented on index.html
> +     </ul>
- [ ] [OPTIONAL] Thank you for fixing this issue that the previous reviewer mentioned. They forgot to mention that the icons should also be in a link tag. These icons would technically be linking to their respective social media URL. so it's best to put the `img` tags inside an `a ` tag that denotes that they are links to other websites I've made it optional but implementing this feature would be nice🙏.

2021-11-26 22:58 UTC, MrBrN197 commented on styles.css
>    font-family: Arial, Helvetica, sans-serif;
- [ ] [OPTIONAL] Please ensure that if you are matching the Figma template as best as you can you should ensure to use the correct fonts as well. I notice here these are not the correct fonts for your template. please correct this. the correct font is `Roboto` please replace this.
- [ ] Please ensure you fix this also on every other line where you use `font-family` 👍

2021-11-27 14:54 UTC, Cathella approved these changes
## 🟢 PROJECT: APPROVED 💪🏻 

### Hi @IfzaRasool 👋🏻, 

Your have done a tremendous job implementing changes that were requested by the previous reviewers 👏🏻. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 14:59 UTC, merged