Work Page
IfzaRasool/Portfolio-setup-and-mobile-version-skeleton pull request #3
Opened 2021-11-27 20:18 UTC by IfzaRasool

Is a recent post page where you upload your post and describe your page.

2021-11-27 22:07 UTC, andersonlebon requested changes
Hi @IfzaRasool 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-27 22:07 UTC, andersonlebon commented on index.html
> +                <div class="button"><img src="Icons/seeproject.png" alt="button"></div>
- [ ] On of the requirements says that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `<ul>` and each of them a `<li>`. Just like this :point_down: 
```
 <ul class="tools">
      <li>css </li>
      <li>html</li>
      <li>bootstrap</li>
      <li>Ruby</li>
</ul>

```

2021-11-27 22:07 UTC, andersonlebon commented on index.html
> +                </div>
## The same thing here

- [ ] On of the requirements says that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `<ul>` and each of them a `<li>`. Just like this :point_down: 
```
 <ul class="tools">
      <li>css </li>
      <li>html</li>
      <li>bootstrap</li>
      <li>Ruby</li>
</ul>

```

2021-11-27 22:07 UTC, andersonlebon commented on index.html
> +                </div>
## The same thing here

- [ ] On of the requirements says that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `<ul>` and each of them a `<li>`. Just like this :point_down: 
```
 <ul class="tools">
      <li>css </li>
      <li>html</li>
      <li>bootstrap</li>
      <li>Ruby</li>
</ul>

```

2021-11-27 22:07 UTC, andersonlebon commented on index.html
> +                </div>
## The same thing here

- [ ] On of the requirements says that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `<ul>` and each of them a `<li>`. Just like this :point_down: 
```
 <ul class="tools">
      <li>css </li>
      <li>html</li>
      <li>bootstrap</li>
      <li>Ruby</li>
</ul>

```

2021-11-27 22:44 UTC, merged

2022-03-21 09:53 UTC, IfzaRasool reviewed
optional changes

2022-03-21 09:53 UTC, IfzaRasool commented on index.html
> +        <section class="main-work-section">
> Use div instead section

2022-03-21 09:53 UTC, IfzaRasool commented on index.html
> +                </div>
ddsss